### ISSUE TITLE
0MB file size?

### ISSUE THREAD

**Issue by MetalMake64** [ai-enma/xdown#1]
I may be doing something wrong. First it didn't recognize wget as command so I added it to path. Now it seems to complete but the file is 0MB.

←[1;32m OK ←[0;0m File mod
←[1;35m ?? ←[0;0m Quality: ←[1;32mHIGH←[0;0m
←[1;35m ?? ←[0;0m Domain:←[1;31m  XVIDEOS←[0;0m
←[1;35m ?? ←[0;0m Output directory: '←[1;35mvideos←[0;0m'
←[1;36m----←[0;0m Downloading '←[1;35mxxxxxx.mp4←[0;0m'
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
 OK  Downloaded 'xxxxxxx.mp4'

**Comment by ai-enma** [comment]
i will update it to remove wget requirement

**Comment by ai-enma** [comment]
Just fixed
